import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import bcrypt from "bcryptjs";

type SeedSqlOptions = {
  ownerEmail: string;
  ownerPasswordHash: string;
  now?: string;
};

type SqlValue = string | number | boolean | null | SqlRaw;

class SqlRaw {
  constructor(readonly value: string) {}
}

function raw(value: string) {
  return new SqlRaw(value);
}

function escapeSql(value: string) {
  return value.replaceAll("'", "''");
}

function valueSql(value: SqlValue) {
  if (value instanceof SqlRaw) {
    return value.value;
  }
  if (value === null) {
    return "NULL";
  }
  if (typeof value === "number") {
    return String(value);
  }
  if (typeof value === "boolean") {
    return value ? "1" : "0";
  }
  return `'${escapeSql(value)}'`;
}

function quoteIdentifier(identifier: string) {
  return `"${identifier.replaceAll('"', '""')}"`;
}

function upsertSql(table: string, data: Record<string, SqlValue>, conflictColumns: string[], updateColumns: string[]) {
  const columns = Object.keys(data);
  const insertColumns = columns.map(quoteIdentifier).join(", ");
  const values = columns.map((column) => valueSql(data[column])).join(", ");
  const conflict = conflictColumns.map(quoteIdentifier).join(", ");
  const updates = updateColumns.map((column) => `${quoteIdentifier(column)} = excluded.${quoteIdentifier(column)}`).join(", ");

  return [
    `INSERT INTO ${quoteIdentifier(table)} (${insertColumns})`,
    `VALUES (${values})`,
    `ON CONFLICT(${conflict}) DO UPDATE SET ${updates};`
  ].join("\n");
}

function ownerIdSubquery(ownerEmail: string) {
  return raw(`(SELECT "id" FROM "User" WHERE "email" = '${escapeSql(ownerEmail)}')`);
}

export function generateD1SeedSql(options: SeedSqlOptions) {
  const now = options.now ?? new Date().toISOString();
  const ownerEmail = options.ownerEmail;
  const ownerId = ownerIdSubquery(ownerEmail);
  const statements: string[] = [
    "-- Generated by prisma/seed-d1.ts. Safe to run more than once.",
    "PRAGMA foreign_keys = ON;",
    upsertSql(
      "User",
      {
        id: "seed-owner",
        email: ownerEmail,
        name: "站点主人",
        passwordHash: options.ownerPasswordHash,
        role: "OWNER",
        disabledAt: null,
        createdAt: now,
        updatedAt: now
      },
      ["email"],
      ["name", "passwordHash", "role", "disabledAt", "updatedAt"]
    ),
    upsertSql(
      "SiteSetting",
      {
        id: "site",
        title: "Like Zhizhi",
        slogan: "每一个日子都普通，除了遇见你的那一天。",
        description: "一个从零重建的情侣纪念站。",
        togetherDate: "2024-05-19T16:00:00.000Z",
        footerText: "Like Zhizhi",
        icpText: null,
        policeText: null,
        seoKeywords: "",
        createdAt: now,
        updatedAt: now
      },
      ["id"],
      ["title", "slogan", "description", "togetherDate", "footerText", "updatedAt"]
    ),
    upsertSql(
      "ThemeSetting",
      {
        id: "theme",
        primaryColor: "#f45d7a",
        backgroundImageUrl: null,
        backgroundVideoUrl: null,
        enableGlassEffect: true,
        enablePageAnimation: true,
        bodyFontKey: null,
        displayFontKey: null,
        romanceFontKey: null,
        numberFontKey: null,
        createdAt: now,
        updatedAt: now
      },
      ["id"],
      ["updatedAt"]
    ),
    upsertSql(
      "PersonProfile",
      {
        id: "seed-person-1",
        slot: 1,
        displayName: "知知",
        avatarUrl: null,
        birthday: null,
        location: "Shanghai",
        bio: "喜欢记录生活里的小事。",
        createdAt: now,
        updatedAt: now
      },
      ["slot"],
      ["displayName", "location", "bio", "updatedAt"]
    ),
    upsertSql(
      "PersonProfile",
      {
        id: "seed-person-2",
        slot: 2,
        displayName: "只只",
        avatarUrl: null,
        birthday: null,
        location: "Hangzhou",
        bio: "负责把愿望一点点实现。",
        createdAt: now,
        updatedAt: now
      },
      ["slot"],
      ["displayName", "location", "bio", "updatedAt"]
    )
  ];

  const modules = [
    ["seed-module-home", "home", "首页", 0],
    ["seed-module-notes", "notes", "点滴", 10],
    ["seed-module-messages", "messages", "留言", 20],
    ["seed-module-footprints", "footprints", "轨迹", 30],
    ["seed-module-album", "album", "相册", 40],
    ["seed-module-checklist", "checklist", "清单", 50],
    ["seed-module-love-days", "love-days", "纪念日", 60],
    ["seed-module-about", "about", "关于", 70]
  ] as const;

  for (const [id, key, label, sortOrder] of modules) {
    statements.push(
      upsertSql(
        "ModuleSetting",
        { id, key, label, enabled: true, sortOrder, description: "", createdAt: now, updatedAt: now },
        ["key"],
        ["label", "enabled", "sortOrder", "updatedAt"]
      )
    );
  }

  statements.push(
    upsertSql(
      "Note",
      {
        id: "seed-note-first-memory",
        slug: "first-memory",
        title: "第一条点滴",
        excerpt: "这是 Phase 1 的种子内容，用来证明首页和后台可以读取数据库。",
        content: "等公共站阶段开始，这里会变成完整的图文时间线。",
        status: "PUBLISHED",
        mood: "开心",
        weather: "晴",
        location: "家",
        authorId: ownerId,
        publishedAt: "2024-05-20T12:00:00.000Z",
        createdAt: now,
        updatedAt: now
      },
      ["slug"],
      ["title", "excerpt", "content", "status", "mood", "weather", "location", "authorId", "publishedAt", "updatedAt"]
    ),
    upsertSql(
      "Message",
      {
        id: "seed-message",
        nickname: "访客",
        content: "祝你们一直热爱生活。",
        status: "APPROVED",
        ipHash: null,
        userAgent: null,
        location: "Local",
        deviceLabel: null,
        createdAt: now
      },
      ["id"],
      ["nickname", "content", "status", "location"]
    ),
    upsertSql(
      "ChecklistItem",
      {
        id: "seed-checklist",
        title: "一起看一次海",
        description: "Phase 1 的愿望清单种子数据。",
        status: "PUBLISHED",
        completed: false,
        completedAt: null,
        targetDate: null,
        location: null,
        imageUrl: null,
        sortOrder: 1,
        createdAt: now,
        updatedAt: now
      },
      ["id"],
      ["title", "description", "status", "completed", "sortOrder", "updatedAt"]
    ),
    upsertSql(
      "LoveDayEvent",
      {
        id: "seed-love-day",
        title: "在一起",
        description: "纪念我们开始认真记录彼此的日子。",
        date: "2024-05-19T16:00:00.000Z",
        yearly: true,
        lunar: false,
        sortOrder: 1,
        createdAt: now,
        updatedAt: now
      },
      ["id"],
      ["title", "description", "date", "yearly", "lunar", "sortOrder", "updatedAt"]
    ),
    upsertSql(
      "MediaAsset",
      {
        id: "seed-media-sunset",
        type: "IMAGE",
        bucket: "like-zhizhi-media",
        objectKey: "seed/sunset.jpg",
        publicUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
        filename: "sunset.jpg",
        contentType: "image/jpeg",
        sizeBytes: 128000,
        width: 1600,
        height: 1067,
        createdAt: now
      },
      ["id"],
      ["type", "bucket", "objectKey", "publicUrl", "filename", "contentType", "sizeBytes", "width", "height"]
    ),
    upsertSql(
      "AlbumItem",
      {
        id: "seed-album-sunset",
        mediaId: "seed-media-sunset",
        title: "海边日落",
        caption: "把傍晚的风和光一起收藏。",
        status: "PUBLISHED",
        takenAt: "2025-08-16T10:30:00.000Z",
        location: "舟山",
        authorLabel: "知知",
        sortOrder: 1,
        createdAt: now,
        updatedAt: now
      },
      ["id"],
      ["mediaId", "title", "caption", "status", "takenAt", "location", "authorLabel", "sortOrder", "updatedAt"]
    )
  );

  const footprints = [
    {
      id: "seed-place-changsha",
      memoryId: "seed-memory-changsha-orange-isle",
      imageId: "seed-memory-image-changsha-orange-isle",
      name: "长沙",
      description: "第一站留给一起吹过江风的城市。",
      latitude: "28.2282000",
      longitude: "112.9388000",
      amapAdcode: "430100",
      amapCityCode: "0731",
      coverUrl: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9",
      sortOrder: 1,
      locationName: "橘子洲",
      address: "湖南省长沙市岳麓区橘子洲头",
      visitedAt: "2024-04-30T16:00:00.000Z",
      mood: "那天江边的风刚刚好",
      story: "把第一段旅程放在长沙，是因为这里有热闹的街和慢下来的黄昏。"
    },
    {
      id: "seed-place-shanghai",
      memoryId: "seed-memory-shanghai-bund",
      imageId: "seed-memory-image-shanghai-bund",
      name: "上海",
      description: "把外滩的灯光也放进我们的路线里。",
      latitude: "31.2304000",
      longitude: "121.4737000",
      amapAdcode: "310000",
      amapCityCode: "021",
      coverUrl: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9",
      sortOrder: 2,
      locationName: "外滩",
      address: "上海市黄浦区中山东一路",
      visitedAt: "2025-09-03T12:00:00.000Z",
      mood: "那天风很轻，适合慢慢走",
      story: "一起走过江边，看灯光慢慢亮起来。"
    }
  ];

  for (const footprint of footprints) {
    statements.push(
      upsertSql(
        "FootprintPlace",
        {
          id: footprint.id,
          name: footprint.name,
          description: footprint.description,
          latitude: footprint.latitude,
          longitude: footprint.longitude,
          amapAdcode: footprint.amapAdcode,
          amapCityCode: footprint.amapCityCode,
          coverUrl: footprint.coverUrl,
          sortOrder: footprint.sortOrder,
          enabled: true,
          createdAt: now,
          updatedAt: now
        },
        ["id"],
        ["name", "description", "latitude", "longitude", "amapAdcode", "amapCityCode", "coverUrl", "sortOrder", "enabled", "updatedAt"]
      ),
      upsertSql(
        "FootprintMemory",
        {
          id: footprint.memoryId,
          placeId: footprint.id,
          locationName: footprint.locationName,
          address: footprint.address,
          amapPoiId: null,
          latitude: null,
          longitude: null,
          visitedAt: footprint.visitedAt,
          mood: footprint.mood,
          story: footprint.story,
          sortOrder: 1,
          createdAt: now,
          updatedAt: now
        },
        ["id"],
        ["placeId", "locationName", "address", "visitedAt", "mood", "story", "sortOrder", "updatedAt"]
      ),
      upsertSql(
        "FootprintMemoryImage",
        {
          id: footprint.imageId,
          memoryId: footprint.memoryId,
          mediaAssetId: "seed-media-sunset",
          sortOrder: 0,
          caption: footprint.locationName,
          createdAt: now
        },
        ["memoryId", "mediaAssetId"],
        ["sortOrder", "caption"]
      )
    );
  }

  statements.push(
    upsertSql(
      "DailyStat",
      {
        id: "seed-daily-stat-2026-05-15",
        date: "2026-05-14T16:00:00.000Z",
        visits: 128,
        uniqueVisitors: 42,
        messages: 1,
        notes: 1
      },
      ["date"],
      ["visits", "uniqueVisitors", "messages", "notes"]
    )
  );

  return `${statements.join("\n\n")}\n`;
}

async function main() {
  const target = process.argv.includes("--remote") ? "--remote" : "--local";
  const ownerEmail = process.env.SEED_OWNER_EMAIL ?? "owner@example.com";
  const ownerPassword = process.env.SEED_OWNER_PASSWORD ?? "ChangeMe123!";
  const ownerPasswordHash = await bcrypt.hash(ownerPassword, 12);
  const sql = generateD1SeedSql({ ownerEmail, ownerPasswordHash });
  const outputPath = resolve(".generated", "d1-seed.sql");

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, sql, "utf8");

  const wranglerArgs = ["wrangler", "d1", "execute", "like-zhizhi", target, "--file", outputPath];
  const command = process.platform === "win32" ? "cmd.exe" : "pnpm";
  const args = process.platform === "win32" ? ["/d", "/s", "/c", "pnpm", ...wranglerArgs] : wranglerArgs;
  const result = spawnSync(command, args, { stdio: "inherit" });

  if (result.error) {
    console.error(result.error);
    process.exit(1);
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

const currentFile = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === currentFile) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
